name: tasky
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.3
  flutter_popup: ^3.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  haptic_feedback: ^0.5.1+1
  intl_phone_field: ^3.2.0
  json_serializable: ^6.9.0
  phone_input: ^1.0.0
  pretty_qr_code: ^3.3.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit_generator: ^9.1.5
flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
  # example:
  fonts:
    - family: sans
      fonts:
        - asset: fonts/DmSans/DMSans-Thin.ttf
        - asset: fonts/DmSans/DMSans-ExtraLight.ttf
        - asset: fonts/DmSans/DMSans_18pt-Light.ttf
        - asset: fonts/DmSans/DMSans-Regular.ttf
        - asset: fonts/DmSans/DMSans-Medium.ttf
        - asset: fonts/DmSans/DMSans-Bold.ttf
        - asset: fonts/DmSans/DMSans-SemiBold.ttf
        - asset: fonts/DmSans/DMSans-ExtraBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
