name: tasky
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.3
  flutter_popup: ^3.3.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  haptic_feedback: ^0.5.1+1
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  pretty_dio_logger: ^1.4.0
  pretty_qr_code: ^3.3.0
  qr_code_scanner_plus: ^2.0.6
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

"// To add assets to your application, add an assets section, like this": null
flutter_assets:
  assets_path:
    - assets/images/
    - assets/svgs/
  output_path: lib/core/constants/
  filename: app_images.dart
  field_prefix: null

  fonts:
    - family: sans
      fonts:
        - asset: fonts/DmSans/DMSans-Thin.ttf
        - asset: fonts/DmSans/DMSans-ExtraLight.ttf
        - asset: fonts/DmSans/DMSans_18pt-Light.ttf
        - asset: fonts/DmSans/DMSans-Regular.ttf
        - asset: fonts/DmSans/DMSans-Medium.ttf
        - asset: fonts/DmSans/DMSans-Bold.ttf
        - asset: fonts/DmSans/DMSans-SemiBold.ttf
        - asset: fonts/DmSans/DMSans-ExtraBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
